spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/open_banking?currentSchema=banking_protocol
    username: postgres
    password: docker
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: banking_protocol

pkcs12:
  keyStore: sample-qwac.keystore
  password: password

xs2a-profile:
  id: 53c47f54-b9a4-465a-8f77-bc6cd5f0cf46
  aspspName: adorsys xs2a
  bic: ADORSYS
  url: http://localhost:10014
  adapterId: adorsys-integ-adapter
  idpUrl:
  aspspScaApproaches:

flowable:
  process-definition-location-prefix: classpath*:/processes/xs2a/