spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/open-banking?currentSchema=banking-protocol
    username: postgres
    password: docker
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: banking-protocol