server:
  port: 8086
  controller:
    cookie:
      secure: false
      maxAge: 300
      httpOnly: false
      path: /
      sameSite: Strict
      # sameSite: Strict|Lax|none
      # samesite SameSite prevents the browser from sending this cookie along with cross-site requests. Possible values for the flag are lax or strict.
      # The strict value will prevent the cookie from being sent by the browser to the target site in all cross-site browsing context, even when following a regular link.
      # The lax value will only send cookies for TOP LEVEL navigation GET requests. This is sufficient for user tracking, but it will prevent many CSRF attacks.



tpp:
  url: http://localhost:8085

mock:
  tppais:
    listtransactions: false
    listaccounts: false

spring:
  datasource:
    url: jdbc:postgresql://localhost/open_banking?currentSchema=fintech
    username: postgres
    password: docker
  liquibase:
    change-log: classpath:master.xml

fintech-ui:
  redirect-url: http://localhost:4444/{redirectUri}/{redirectCode}
  exception-url: http://localhost:4444/excaption-redirect
