server:
  port: 8086
  controller:
    cookie:
      secure: false
      maxAge: 300
      httpOnly: false
      path: /
tpp:
  url: http://localhost:18085

mock:
  tppais:
    listtransactions: true
    listaccounts: false

java:
  net:
    HttpURLConnection:
      followRedirects: false

feign:
  httpclient:
    follow-redirects: false
  client:
    config:
      default:
        followRedirects: false

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: SA
    password:
    driver-class-name: org.h2.Driver

