spring:
  profiles.include:
    - swagger
    - file-persistence
    - disable-security
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

springdoc:
  packagesToScan: de.adorsys.smartanalytics.web

smartanalytics:
  conf:
    path: classpath:smart-analytics-rules